version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3111:3000"
    volumes:
      - ./.env:/usr/src/app/.env
      - ./users.json:/usr/src/app/users.json
      - ./query_log.txt:/usr/src/app/query_log.txt
      - ./elements.js:/usr/src/app/elements.js